nm('f' ,'?')
nm('x', ':redo<cr>')
nm('z',':undo<cr>')
nm('r', ':source %<cr>:PackerInstall<cr>')
nm('s', ':w<cr>')
nm('a', ':q<cr>')
nm('.', 'w')
nm(',', 'b')
nm('<C-.>', '$')
nm('<C-,>', '0')
-- input mode
im('jk', '<esc>')
im('<A-s>', '<esc>:w<cr>i')
im('<A-a>', '<esc>:wq<cr>')
im('<A-z>', '<esc>:undo<cr>i')
im('<A-x>', '<esc>:redo<cr>i')
im('<A-,>','<esc>bi')
im('<A-.>','<esc>wi')
im('<C-A-,>', '<esc>0i')
im('<C-A-.>', '<esc>$i')
im('<C-f>','<esc>?')
im('<C-d>','<esc>$v0c<esc>$pi<right><cr><esc>$pi<right>')
im('<C-c>','<esc>$v0c<esc>$pi<right>')
im('<C-x>','<esc>$v0c')
im('<C-S-d>','<esc>$vDi')
im('<A-/>','<esc>:Commentary<cr>i')
