nm('f' ,'?')
nm('Z', ':redo<cr>')
nm('z',':undo<cr>')
nm('r', ':source %<cr>:PackerInstall<cr>')
nm('s', ':w<cr>')
nm('q', ':q<cr>')
nm('.', 'w')
nm(',', 'b')
nm('<C-.>', '$')
nm('<C-,>', '0')
-- input mode
im('<A-s>', '<esc>:w<c
im('<C-A-,>', '<esc>0i')
im('<C-A-.>', '<esc>$i')
im('<C-f>','<esc>?')
nm('d','$v0c<esc>$pi<right><cr><esc>$pi<right>')
nm('x','$v0c<esc>$pi<right><cr><esc>$pi<right>')
nm('/',':Commentary<cr>i')
