nm('f' ,'?')
nm('Z', ':redo<cr>')
nm('z',':undo<cr>')
nm('r', ':source %<cr>:PackerInstall<cr>')
nm('s', ':w<cr>')
nm('q', ':q<cr>')
nm('.', 'w')
nm(',', 'b')
nm('<C-.>', '$')
nm('<C-,>', '0')
nm('d','$v0c<esc>$pi<right><cr><esc>$pi<right>')
nm('c','$v0c<esc>$')
nm('/',':Commentary<cr>i')
