nm('f' ,'?')
nm('Z', ':redo<cr>')
nm('z',':undo<cr>')
nm('r', ':source %<cr>:PackerInstall<cr>i')
nm('s', ':w<cr>i')
nm('q', ':q<cr>')
nm('.', 'wi')
nm(',', 'bi')
nm('<C-.>', '$i')
nm('<C-,>', '0i')
nm('d','$v0c<esc>$pi<right><cr><esc>$pi<right>')
nm('c','$v0c<esc>$i')
nm('p','$v0c<esc>$pi<right>')
nm('/',':Commentary<cr>i')
im('<ALT>','<esc>')
nm('<kEnte>','i')
