#! bash oh-my-bash.module

source "$OSH/themes/powerline/powerline.base.sh"

PROMPT_CHAR=${POWERLINE_PROMPT_CHAR:=""}
POWERLINE_LEFT_SEPARATOR=${POWERLINE_LEFT_SEPARATOR:=""}

SCM_NONE_CHAR=""
# SCM_GIT_CHAR=${POWERLINE_SCM_GIT_CHAR:=" "}
SCM_GIT_CHAR=${POWERLINE_SCM_GIT_CHAR:=" "}
SCM_THEME_PROMPT_CLEAN=""
SCM_THEME_PROMPT_DIRTY=""
SCM_THEME_PROMPT_CLEAN_COLOR=60
SCM_THEME_PROMPT_DIRTY_COLOR=52
SCM_THEME_PROMPT_COLOR=${SCM_THEME_PROMPT_CLEAN_COLOR}

CWD_THEME_PROMPT_COLOR=0

THEME_CLOCK_FORMAT=${THEME_CLOCK_FORMAT:="%H:%M:%S"}

POWERLINE_PROMPT=${POWERLINE_PROMPT:="user_info cwd"}

_omb_theme_PROMPT_COMMAND() { __powerline_prompt_command "$@"; }
_omb_util_add_prompt_command _omb_theme_PROMPT_COMMAND
