nm('f' ,'?')
nm('Z', ':redo<cr>')
nm('z',':undo<cr>')
nm('r', ':source %<cr>:PackerInstall<cr>i')
nm('s', ':w<cr>i')
nm('q', ':q<cr>')
nm('.', '$i')
nm(',', '0i')
nm('d','$v0c<esc>$pi<right><cr><esc>$pi<right>')
nm('c','$v0c<esc>$i')
nm('p','$v0c<esc>$pi<right>')
nm('/',':Commentary<cr>i')
nm('<esc>','i<right>')
